import { useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Activity, ArrowLeft, ArrowRight, Award, BookOpen, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Compass, Flame, GraduationCap, Landmark, Layers, Map, Menu, Moon, RotateCcw, Sparkles, Sun, Target, Trophy, Waves, X, Zap } from 'lucide-react'
import { badges, examPrompts, lessons, mapPoints, questions, terms, timeline, trueFalseQuestions, type Question } from './content'
import { ExamReviewPage, PracticeTestsPage, ProgressPage, UnitCatalog, UnitPage, VocabularyPage, type LearningProgress, type RecordStudy } from './CurriculumPages'
import { units } from './curriculum'

type Progress = LearningProgress & { lastStudy: string }
const initial: Progress = { xp: 0, answered: 0, correct: 0, streak: 0, lastStudy: '', completed: [], knownCards: [], weekly: [0, 0, 0, 0, 0, 0, 0], unitStats: {} }
const progressKey = 'unit2-mastery-progress'
const nav = [
  { to: '/', label: 'Dashboard', icon: Activity },
  ...units.map(unit => ({ to: `/unit/${unit.id}`, label: `Unit ${unit.id}`, icon: BookOpen })),
  { to: '/review', label: 'Exam Review', icon: GraduationCap },
  { to: '/vocabulary', label: 'Vocabulary', icon: Layers },
  { to: '/practice-tests', label: 'Practice Tests', icon: Target },
  { to: '/progress', label: 'Progress', icon: Trophy },
]

function loadProgress(): Progress {
  try {
    const saved = JSON.parse(localStorage.getItem(progressKey) ?? 'null') as Partial<Progress> | null
    return { ...initial, ...saved, weekly: saved?.weekly?.length === 7 ? saved.weekly : initial.weekly, unitStats: saved?.unitStats ?? {} }
  } catch { return initial }
}

function App() {
  const [progress, setProgress] = useState<Progress>(loadProgress)
  const [dark, setDark] = useState(() => localStorage.getItem('unit2-mastery-theme') === 'dark')
  const [menuOpen, setMenuOpen] = useState(false)
  const location = useLocation()
  useEffect(() => { localStorage.setItem(progressKey, JSON.stringify(progress)) }, [progress])
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.setItem('unit2-mastery-theme', dark ? 'dark' : 'light') }, [dark])
  useEffect(() => { setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }, [location.pathname])
  const record: RecordStudy = (correct, xp = 10, completion, knownCard, unitId = '2', questionId, activityOnly = false) => setProgress(current => {
    const today = new Date().toDateString(); const yesterday = new Date(Date.now() - 86400000).toDateString(); const weekly = [...current.weekly]; weekly[(new Date().getDay() + 6) % 7] += 1
    const alreadyRecorded = Boolean((completion && current.completed.includes(completion)) || (knownCard && current.knownCards.includes(knownCard)))
    const unitStats = { ...(current.unitStats ?? {}) }
    const previous = unitStats[unitId] ?? { answered: 0, correct: 0, xp: 0, masteredTerms: [], missedQuestions: [] }
    const term = knownCard?.startsWith(`u${unitId}-`) ? knownCard.slice(`u${unitId}-`.length) : unitId === '2' ? knownCard : undefined
    unitStats[unitId] = {
      ...previous,
      answered: previous.answered + Number(!activityOnly),
      correct: previous.correct + Number(!activityOnly && correct),
      xp: previous.xp + (alreadyRecorded ? 0 : xp),
      masteredTerms: term && !previous.masteredTerms.includes(term) ? [...previous.masteredTerms, term] : previous.masteredTerms,
      missedQuestions: questionId ? correct ? previous.missedQuestions.filter(id => id !== questionId) : previous.missedQuestions.includes(questionId) ? previous.missedQuestions : [...previous.missedQuestions, questionId] : previous.missedQuestions,
    }
    return { ...current, unitStats, xp: current.xp + (alreadyRecorded ? 0 : xp), answered: current.answered + Number(!activityOnly), correct: current.correct + Number(!activityOnly && correct), streak: current.lastStudy === today ? current.streak : current.lastStudy === yesterday ? current.streak + 1 : Math.max(1, current.streak), lastStudy: today, weekly, completed: completion && !current.completed.includes(completion) ? [...current.completed, completion] : current.completed, knownCards: knownCard && !current.knownCards.includes(knownCard) ? [...current.knownCards, knownCard] : current.knownCards }
  })
  const mastery = progress.answered ? Math.round(progress.correct / progress.answered * 100) : 0
  const shared = { progress, mastery, record }
  const activeUnit = location.pathname.match(/^\/unit\/(\d+)/)?.[1]
  const activeUnitInfo = activeUnit ? units.find(unit => unit.id === Number(activeUnit)) : undefined
  const breadcrumb = activeUnitInfo ? `UNIT ${activeUnitInfo.id}: ${activeUnitInfo.title.toUpperCase()}` : location.pathname === '/' ? 'THE COMPLETE COURSE · UNITS 1–9' : location.pathname === '/review' ? 'EXAM REVIEW' : location.pathname === '/vocabulary' ? 'ALL-UNIT VOCABULARY' : location.pathname === '/practice-tests' ? 'PRACTICE TESTS' : location.pathname === '/progress' ? 'COURSE PROGRESS' : 'UNIT 2: NETWORKS OF EXCHANGE'
  return <div className="app-shell"><aside className={`sidebar ${menuOpen ? 'sidebar-open' : ''}`}>
    <Link to="/" className="brand"><span className="brand-mark"><Landmark size={20} /></span><span className="brand-name">FIELDNOTES<span>AP WORLD HISTORY</span></span></Link>
    <div className="unit-label">AP WORLD MODERN <span>UNITS 1–9</span></div><nav className="side-nav">{nav.map(({ to, label, icon: Icon }) => <NavLink end={to === '/'} to={to} key={to} className={({ isActive }) => `nav-link ${isActive ? 'nav-active' : ''}`}><Icon size={18} /><span>{label}</span>{to === '/practice-tests' && <span className="nav-count">55</span>}</NavLink>)}</nav>
    <div className="sidebar-course"><div className="course-top"><span className="course-dot" /> COURSE SNAPSHOT</div><strong>AP World: Modern</strong><span>1200 CE — present</span><div className="course-progress"><span style={{ width: `${mastery}%` }} /></div><small>{mastery}% overall activity accuracy</small></div>
    <div className="sidebar-bottom"><span className="avatar">HW</span><div><strong>History learner</strong><small>{progress.xp.toLocaleString()} XP earned</small></div><button className="icon-button theme-toggle" aria-label="Toggle dark mode" title="Toggle dark mode" onClick={() => setDark(!dark)}>{dark ? <Sun size={17} /> : <Moon size={17} />}</button></div>
  </aside>{menuOpen && <button className="mobile-scrim" aria-label="Close menu" onClick={() => setMenuOpen(false)} />}
    <main className="main-area"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={19} /> : <Menu size={19} />}</button><div className="breadcrumbs">AP WORLD HISTORY <ChevronRight size={13} /><span>{breadcrumb}</span></div><div className="topbar-right"><span className="streak-pill"><Flame size={15} /> {progress.streak} day streak</span><span className="xp-pill"><Zap size={14} /> {progress.xp} XP</span></div></header>
      <div className="page-wrap"><AnimatePresence mode="wait"><motion.div key={location.pathname} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -5 }} transition={{ duration: .2 }}><Routes><Route path="/" element={<Dashboard {...shared} />} /><Route path="/unit/:unitId/:section?" element={<UnitPage {...shared} />} /><Route path="/review" element={<ExamReviewPage {...shared} />} /><Route path="/vocabulary" element={<VocabularyPage {...shared} />} /><Route path="/practice-tests" element={<PracticeTestsPage record={record} />} /><Route path="/progress" element={<ProgressPage {...shared} />} /><Route path="/learn" element={<Learn {...shared} />} /><Route path="/flashcards" element={<Flashcards {...shared} />} /><Route path="/practice" element={<Practice {...shared} />} /><Route path="/games" element={<Games {...shared} />} /><Route path="/exam" element={<Exam {...shared} />} /><Route path="*" element={<Dashboard {...shared} />} /></Routes></motion.div></AnimatePresence></div>
    </main><nav className="mobile-dock">{nav.slice(0, 5).map(({ to, label, icon: Icon }) => <NavLink end={to === '/'} to={to} key={to} className={({ isActive }) => isActive ? 'dock-active' : ''}><Icon size={19} /><span>{label}</span></NavLink>)}</nav>
  </div>
}

type Shared = { progress: Progress; mastery: number; record: (correct: boolean, xp?: number, completion?: string, knownCard?: string) => void }
function Heading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="section-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div> }
function Stat({ icon, label, value, sub, color }: { icon: React.ReactNode; label: string; value: string; sub: string; color: string }) { return <div className="stat-card"><div className={`stat-icon ${color}`}>{icon}</div><span className="stat-label">{label}</span><strong className="stat-value">{value}</strong><span className="stat-sub">{sub}</span></div> }

function Dashboard({ progress, mastery }: Shared) {
  const days = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'].map((day, i) => ({ day, sessions: progress.weekly[i] }))
  return <><Heading eyebrow="AP WORLD HISTORY: MODERN · COMPLETE COURSE" title="One connected world" description="Explore all nine AP World Modern units, build historical thinking skills, and prepare for the AP exam from a single learning dashboard." action={<Link to="/practice-tests" className="button button-dark"><Target size={16} /> Full-course practice <ArrowRight size={15} /></Link>} />
    <section className="welcome-banner"><div className="banner-copy"><span className="banner-kicker"><i /> YOUR LEARNING JOURNEY</span><h2>One connected world.<br />Many ways to explore.</h2><p>Goods moved. Ideas traveled. Empires rose along the routes between them.</p><Link to="/learn" className="button button-light">Pick a field guide <ArrowRight size={15} /></Link></div><div className="banner-art"><TradeMap /></div><span className="banner-coordinate">35°N / 72°E</span></section>
    <section className="stats-grid"><Stat icon={<Target size={17} />} label="UNIT MASTERY" value={`${mastery}%`} sub={progress.answered ? `${progress.correct} correct answers` : 'Start with one question'} color="sage" /><Stat icon={<Flame size={17} />} label="CURRENT STREAK" value={`${progress.streak} days`} sub="A little practice adds up" color="clay" /><Stat icon={<Zap size={17} />} label="TOTAL XP" value={progress.xp.toLocaleString()} sub="Earn XP with every session" color="gold" /><Stat icon={<Check size={17} />} label="COMPLETED" value={`${progress.completed.length}`} sub="Activities finished" color="blue" /></section>
    <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">KEEP THE MOMENTUM</span><h3>Study activity</h3></div><span className="period-select">THIS WEEK <ChevronDown size={14} /></span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={days} margin={{ top: 8, right: 8, left: -24, bottom: 0 }}><defs><linearGradient id="activityFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#397567" stopOpacity={.2} /><stop offset="100%" stopColor="#397567" stopOpacity={.01} /></linearGradient></defs><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="var(--line)" /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: 'var(--muted)', fontSize: 10 }} dy={10} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fill: 'var(--muted)', fontSize: 10 }} /><Tooltip contentStyle={{ background: 'var(--surface)', borderColor: 'var(--line)', borderRadius: 6, fontSize: 12 }} /><Area type="monotone" dataKey="sessions" stroke="#397567" strokeWidth={2} fill="url(#activityFill)" /></AreaChart></ResponsiveContainer></div><div className="chart-footer"><span><i /> Study activities</span><span>Small steps, big picture.</span></div></section><section className="panel focus-panel"><div className="panel-heading"><div><span className="eyebrow">NEXT UP</span><h3>A route worth knowing</h3></div><span className="focus-icon"><Compass size={19} /></span></div><div className="focus-map"><TradeMap compact /></div><div className="focus-info"><div><span className="route-tag">THE SILK ROADS</span><p>How did caravans make a journey across Eurasia possible?</p></div><Link to="/learn" className="circle-link" aria-label="Open Silk Roads lesson"><ArrowRight size={17} /></Link></div></section></div>
    <section className="recent-section"><div className="panel-heading"><div><span className="eyebrow">EXPLORE THE UNIT</span><h3>Choose a route</h3></div><Link className="text-link" to="/learn">All lessons <ArrowRight size={14} /></Link></div><div className="lesson-row">{lessons.slice(0, 3).map((lesson, i) => <Link to="/learn" className="lesson-row-item" key={lesson.id}><span className={`lesson-icon ${lesson.color}`}><Map size={18} /></span><span className="lesson-label"><small>FIELD GUIDE · {i + 1}</small><strong>{lesson.label}</strong></span><ArrowRight size={16} className="row-arrow" /></Link>)}</div></section>
    <section className="badges-section"><div><span className="eyebrow">BADGES · YOUR NEXT MILESTONE</span><div className="badges-row">{badges.map(badge => <span key={badge.name} className={`badge-chip ${progress.xp >= badge.threshold * 10 ? 'badge-earned' : ''}`} title={`${badge.name} · ${badge.threshold * 10} XP`}><Award size={14} />{badge.name}</span>)}</div></div></section>
    <UnitCatalog progress={progress} />
    <div className="unit-footnote"><span>AP WORLD HISTORY: MODERN · c. 1200–PRESENT</span><span>Nine units <i>·</i> historical thinking <i>·</i> exam practice</span></div>
  </>
}

function TradeMap({ compact = false }: { compact?: boolean }) {
  return <svg className={`trade-map ${compact ? 'trade-map-compact' : ''}`} viewBox="0 0 700 310" role="img" aria-label="Illustrated Afro-Eurasian trade network map"><defs><pattern id="mapGrid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0V24" fill="none" stroke="currentColor" strokeOpacity=".09" strokeWidth=".6" /></pattern></defs><rect width="700" height="310" fill="url(#mapGrid)" /><path className="continent" d="m80 112 25-30 47-13 32 8 31-20 50 5 34 15 36-9 33 12 24-9 35 20 38-11 38 12 37 16 34-2 39 20 25 26-23 15-28-6-17 20-25 1-21 17-32-9-22 19-23-15-25 11-27-12-17 19-34-10-24 13-21-19-23-1-20-23-27-1-15-21-22-6-14 13-24-13-22 4-21-14-23 3Z" /><path className="continent" d="m188 166 28-10 28 10 16 18 6 20-14 22-11 26-20 12-11-20-16-18-5-22-14-16Z" /><path className="continent" d="m411 211 24-5 17 15-3 22-17 11-14-10-13-18Z" /><path className="route-line route-silk" d="M118 118Q215 45 323 112t169 27" /><path className="route-line route-ocean" d="M488 153Q446 220 364 235t-118 10" /><path className="route-line route-sahara" d="M217 167q40-24 80-4t55-8" /><circle className="map-dot dot-silk" cx="118" cy="118" r="4" /><circle className="map-dot dot-silk" cx="323" cy="112" r="4" /><circle className="map-dot dot-silk" cx="492" cy="139" r="4" /><circle className="map-dot dot-ocean" cx="488" cy="153" r="4" /><circle className="map-dot dot-ocean" cx="364" cy="235" r="4" /><circle className="map-dot dot-sahara" cx="297" cy="163" r="4" /><text className="map-label" x="83" y="105">CHANG’AN</text><text className="map-label" x="293" y="98">SAMARKAND</text><text className="map-label" x="461" y="130">CALICUT</text><text className="map-label" x="345" y="259">KILWA</text><text className="map-route-label" x="220" y="81">SILK ROADS</text><text className="map-route-label" x="390" y="210">SEA ROADS</text><text className="map-route-label" x="245" y="148">SAND ROADS</text></svg>
}

function Learn({ record }: Shared) {
  const [selected, setSelected] = useState(lessons[0].id); const [place, setPlace] = useState<string | null>(null); const [spread, setSpread] = useState(0); const [phase, setPhase] = useState<number | null>(null)
  const lesson = lessons.find(item => item.id === selected) ?? lessons[0]
  return <><Heading eyebrow="LEARN MODE · GUIDED FIELD GUIDES" title="Follow the exchange" description="Six field guides trace how goods, beliefs, technology, and disease moved from 1200 to 1450." action={<span className="content-count"><BookOpen size={15} /> 6 FIELD GUIDES</span>} /><div className="learn-layout"><aside className="lesson-index"><span className="eyebrow">THE FIELD GUIDE</span>{lessons.map((item, i) => <button key={item.id} className={`lesson-index-item ${selected === item.id ? 'selected' : ''}`} onClick={() => { setSelected(item.id); setPlace(null) }}><span className="index-number">0{i + 1}</span><span><strong>{item.label}</strong><small>{item.subtitle}</small></span><ChevronRight size={15} /></button>)}<div className="skill-note"><Sparkles size={16} /><strong>Think like a historian</strong><p>Notice what changes when goods, people, and ideas move.</p></div></aside>
      <article className="lesson-content"><div className={`lesson-hero ${lesson.color}`}><span className="eyebrow">FIELD GUIDE / {String(lessons.findIndex(item => item.id === selected) + 1).padStart(2, '0')}</span><h2>{lesson.label}</h2><p>{lesson.summary}</p><span className="hero-stamp">1200 — 1450<br />CE</span></div><div className="lesson-body"><span className="eyebrow">THE BIG PICTURE</span><h3>Follow the connections</h3><p className="body-copy">{lesson.key} Trade connected Afro-Eurasia and altered consumption, encouraged labor specialization and mobility, and raised questions of who controlled exchange.</p><div className="concept-strip"><span className="concept-number">01</span><div><strong>Movement creates connection</strong><p>Exchange networks linked faraway communities through shared routes, markets, and ports.</p></div></div><span className="eyebrow">INTERACTIVE ROUTE MAP</span><h3>Trace the network</h3><p className="map-instruction">Choose a place to open its field note.</p><div className="interactive-map"><TradeMap compact /><div className="map-locations">{mapPoints.map(point => <button key={point.name} className={place === point.name ? 'location-active' : ''} onClick={() => setPlace(point.name)}><i />{point.name}</button>)}</div>{place && <div className="map-note"><Map size={15} /><p><strong>{place}:</strong> {mapPoints.find(point => point.name === place)?.note}</p><button className="icon-button" aria-label="Dismiss" onClick={() => setPlace(null)}><X size={15} /></button></div>}</div>
        {selected === 'beliefs' && <div className="activity-block"><span className="eyebrow">FOLLOW A BELIEF</span><h3>Buddhism along the Silk Roads</h3><p>Merchants and monasteries carried Buddhist traditions north and east. Select each stop to trace that journey.</p><div className="spread-track">{['India', 'Central Asia', 'East Asia'].map((stop, i) => <button className={spread >= i ? 'spread-reached' : ''} key={stop} onClick={() => { setSpread(i); record(true, 1) }}><span>{spread > i ? <Check size={13} /> : i + 1}</span>{stop}</button>)}</div><div className="branch-note"><strong>Adaptation matters</strong><p>Mahayana Buddhism became especially influential in Central and East Asia; Theravada traditions remained influential in South and Southeast Asia.</p></div></div>}
        {selected === 'disease' && <div className="activity-block"><span className="eyebrow">DISEASE TIMELINE</span><h3>When connections carried contagion</h3><div className="disease-timeline">{[['c. 1330s', 'Plague outbreaks in Central Asia'], ['1347', 'Disease reaches Mediterranean ports'], ['1348–49', 'The Black Death spreads across Europe'], ['1351', 'The pandemic recedes, leaving lasting demographic change']].map(([year, event]) => <div key={year}><small>{year}</small><i /><p>{event}</p></div>)}</div><p>Plague, smallpox, malaria, and measles were among the diseases that moved through connected populations.</p></div>}
        {selected === 'mongol' && <div className="phase-strip"><span className="eyebrow">FOUR PHASES OF THE MONGOL EMPIRE</span><div>{['Unification · 1206', 'Conquest', 'Pax Mongolica', 'Fragmentation'].map((item, i) => <button key={item} className={phase === i ? 'phase-highlight' : ''} onClick={() => setPhase(i)}>{item}<small>{['Temujin unites Mongol tribes under merit-based leadership.','Mobile cavalry, discipline, organization, and intimidation support expansion.','Messenger systems and passports protect merchants and travel.','Golden Horde, Chagatai Khanate, Ilkhanate, and Yuan Dynasty.'][i]}</small></button>)}</div></div>}
        {selected === 'ocean' && <div className="activity-block"><span className="eyebrow">MONSOON WIND SIMULATOR</span><h3>Time the crossing</h3><p>Indian Ocean winds reverse seasonally. Pick a season to see how a merchant plans a round trip.</p><div className="wind-control"><button onClick={() => setPhase(phase === 1 ? 0 : 1)}><Waves size={16} /> {phase === 1 ? 'Return winds · Nov–Mar' : 'Outbound winds · Jun–Sep'}</button><span className={phase === 1 ? 'wind-arrow reverse' : 'wind-arrow'}>→</span><span>{phase === 1 ? 'Return to East Africa' : 'Sail toward South Asia'}</span></div></div>}
        <div className="grid grid-cols-2 gap-2 my-3">{[['Cause & effect', 'Explain how conditions produced consequences.'], ['Comparison', 'Use a shared criterion to explain meaningful similarities or differences.'], ['Continuity & change', 'Trace what persisted and what shifted across 1200–1450.'], ['Historical developments', 'Situate events in context and explain their significance.']].map(([skill, detail]) => <div key={skill} className="rounded border border-[color:var(--line)] bg-[color:var(--surface-2)] p-2"><strong className="text-[10px] text-[color:var(--green)]">{skill}</strong><p className="m-0 mt-1 text-[9px] leading-relaxed text-[color:var(--muted)]">{detail}</p></div>)}</div><div className="lesson-takeaway"><Sparkles size={16} /><p><strong>AP skill · Cause &amp; effect</strong><br />Explain how geography or political stability enabled exchange, then trace a consequence for people or states.</p></div><button className="button button-dark" onClick={() => record(true, 25, `lesson-${selected}`)}><Check size={15} /> Mark guide complete <span>+25 XP</span></button></div></article></div></>
}

function Flashcards({ progress, record }: Shared) {
  const [index, setIndex] = useState(0); const [flipped, setFlipped] = useState(false); const [filter, setFilter] = useState('All terms')
  const choices = ['All terms', ...new Set(terms.map(term => term.network))]; const deck = terms.filter(term => filter === 'All terms' || term.network === filter); const card = deck[index % deck.length]
  const knownCount = terms.filter(term => progress.knownCards.includes(term.term) || progress.knownCards.includes(`u2-${term.term}`)).length
  const move = (by: number) => { setIndex(i => (i + by + deck.length) % deck.length); setFlipped(false) }
  return <><Heading eyebrow="FLASHCARDS · SPACED REVIEW" title="Keep the key terms close" description="Flip, recall, and sort essential vocabulary. Your progress stays on this device." action={<span className="content-count"><Layers size={15} /> {deck.length} CARDS</span>} /><div className="flashcard-layout"><aside className="flashcard-side"><span className="eyebrow">STUDY SET</span><h3>Networks of Exchange</h3><p>Essential Unit 2 vocabulary.</p><label className="filter-label" htmlFor="term-filter">FILTER BY NETWORK</label><div className="select-wrap"><select id="term-filter" value={filter} onChange={e => { setFilter(e.target.value); setIndex(0); setFlipped(false) }}>{choices.map(value => <option key={value}>{value}</option>)}</select><ChevronDown size={15} /></div><div className="card-progress"><div><span>YOUR PROGRESS</span><strong>{knownCount} / {terms.length}</strong></div><div className="progress-track"><i style={{ width: `${knownCount / terms.length * 100}%` }} /></div></div><div className="review-hint"><RotateCcw size={16} /><p><strong>Spaced repetition</strong><br />Mark tricky cards for another pass. Review whenever you have a spare minute.</p></div></aside><div className="flashcard-main"><div className="flashcard-topline"><span>TERM <b>{String(index + 1).padStart(2, '0')}</b> OF {String(deck.length).padStart(2, '0')}</span><span>{card.network}</span></div><button className="flashcard" onClick={() => setFlipped(!flipped)} aria-label="Flip flashcard"><AnimatePresence mode="wait"><motion.div key={flipped ? 'back' : 'front'} initial={{ opacity: 0, rotateX: -8 }} animate={{ opacity: 1, rotateX: 0 }} exit={{ opacity: 0, rotateX: 8 }} className="flashcard-inner">{flipped ? <><span className="eyebrow">DEFINITION</span><p className="card-definition">{card.definition}</p><span className="card-turn">CLICK TO SEE TERM</span></> : <><span className="eyebrow">WHAT DOES THIS MEAN?</span><h2>{card.term}</h2><span className="card-turn">CLICK TO FLIP</span></>}</motion.div></AnimatePresence><Layers className="flashcard-watermark" size={38} /></button><div className="card-controls"><button className="button button-outline" onClick={() => move(-1)}><ChevronLeft size={17} /> Previous</button><div className="card-dots">{deck.slice(0, 9).map((item, i) => <button aria-label={`Go to ${item.term}`} key={item.term} className={index % Math.min(9, deck.length) === i ? 'active' : ''} onClick={() => { setIndex(i); setFlipped(false) }} />)}</div><button className="button button-outline" onClick={() => move(1)}>Next <ChevronRight size={17} /></button></div><div className="card-sort"><span>HOW WELL DID YOU KNOW IT?</span><div><button className="sort-again" onClick={() => { record(false, 3); move(1) }}><RotateCcw size={15} /> Review again</button><button className="sort-know" onClick={() => { record(true, 8, undefined, card.term); move(1) }}><Check size={15} /> Got it</button></div></div></div></div></>
}

function Practice({ record }: Shared) {
  const [topic, setTopic] = useState('All topics'); const [difficulty, setDifficulty] = useState('All levels'); const [format, setFormat] = useState('Multiple choice'); const [index, setIndex] = useState(0); const [selected, setSelected] = useState<string | null>(null); const [revealed, setRevealed] = useState(false); const [correctCount, setCorrectCount] = useState(0)
  const pool = useMemo(() => questions.filter(q => (topic === 'All topics' || q.topic === topic) && (difficulty === 'All levels' || q.difficulty === difficulty)), [topic, difficulty]); const topics = ['All topics', ...new Set((format === 'True / false' ? trueFalseQuestions : questions).map(q => q.topic))]; const tfPool = trueFalseQuestions.filter(q => topic === 'All topics' || q.topic === topic); const q = pool[index % pool.length]; const tf = tfPool[index % tfPool.length]
  const reset = () => { setIndex(0); setSelected(null); setRevealed(false) }; const next = () => { setIndex(i => i + 1); setSelected(null); setRevealed(false) }
  const check = () => { if (!selected || revealed) return; setRevealed(true); const right = selected === q.answer; record(right, right ? 12 : 3); if (right) setCorrectCount(value => value + 1) }
  const checkTrueFalse = (value: boolean) => { if (revealed) return; setSelected(String(value)); setRevealed(true); record(value === tf.answer, value === tf.answer ? 8 : 2); if (value === tf.answer) setCorrectCount(count => count + 1) }
  return <><Heading eyebrow="PRACTICE · QUESTION BANK" title="Practice the patterns" description="Build confidence with focused questions, then level up to AP-style reasoning." action={<span className="content-count"><CircleHelp size={15} /> {questions.length} MC + {trueFalseQuestions.length} T/F</span>} /><div className="practice-filters"><div><label htmlFor="topic-select">TOPIC</label><div className="select-wrap"><select id="topic-select" value={topic} onChange={e => { setTopic(e.target.value); reset() }}>{topics.map(value => <option key={value}>{value}</option>)}</select><ChevronDown size={15} /></div></div><div><label htmlFor="level-select">DIFFICULTY</label><div className="select-wrap"><select id="level-select" value={difficulty} onChange={e => { setDifficulty(e.target.value); reset() }}>{['All levels', 'Easy', 'Medium', 'AP level'].map(value => <option key={value}>{value}</option>)}</select><ChevronDown size={15} /></div></div><div><label htmlFor="format-select">QUESTION TYPE</label><div className="select-wrap"><select id="format-select" value={format} onChange={e => { setFormat(e.target.value); setTopic('All topics'); reset() }}>{['Multiple choice', 'True / false'].map(value => <option key={value}>{value}</option>)}</select><ChevronDown size={15} /></div></div><span className="question-count">{format === 'True / false' ? `${index % tfPool.length + 1} / ${tfPool.length}` : `${index % pool.length + 1} / ${pool.length}`} · {correctCount} correct</span></div>{format === 'Multiple choice' ? <QuestionCard key={`${q.id}-${index}`} q={q} selected={selected} revealed={revealed} onSelect={setSelected} onCheck={check} onNext={next} /> : <TrueFalseCard key={`${tf.id}-${index}`} item={tf} selected={selected} revealed={revealed} onAnswer={checkTrueFalse} onNext={next} />}<div className="practice-note"><Sparkles size={17} /><div><strong>AP thinking tip</strong><p>For “explain” prompts, make a claim and connect it to specific historical evidence with a clear line of reasoning.</p></div></div></>
}

function QuestionCard({ q, selected, revealed, onSelect, onCheck, onNext }: { q: Question; selected: string | null; revealed: boolean; onSelect: (s: string) => void; onCheck: () => void; onNext: () => void }) {
  return <section className="question-card"><div className="question-meta"><span className="question-topic">{q.topic}</span><span className={`difficulty-tag ${q.difficulty === 'AP level' ? 'difficulty-ap' : ''}`}>{q.difficulty}</span></div><span className="eyebrow">MULTIPLE CHOICE</span><h2>{q.prompt}</h2><div className="answer-list">{q.choices.map((answer, i) => { const right = revealed && answer === q.answer; const wrong = revealed && answer === selected && !right; return <button key={answer} disabled={revealed} className={`answer-option ${selected === answer ? 'answer-selected' : ''} ${right ? 'answer-correct' : ''} ${wrong ? 'answer-wrong' : ''}`} onClick={() => onSelect(answer)}><span className="answer-letter">{String.fromCharCode(65 + i)}</span><span>{answer}</span>{right && <Check size={17} />}{wrong && <X size={17} />}</button> })}</div>{revealed && <div className={`explanation ${selected === q.answer ? '' : 'explanation-review'}`}><strong>{selected === q.answer ? 'Exactly right.' : 'Not quite. Here’s the connection.'}</strong><p>{q.explanation}</p></div>}<div className="question-actions"><button className="button button-dark" disabled={!revealed && !selected} onClick={revealed ? onNext : onCheck}>{revealed ? 'Next question' : 'Check answer'} <ArrowRight size={15} /></button></div></section>
}

function TrueFalseCard({ item, selected, revealed, onAnswer, onNext }: { item: typeof trueFalseQuestions[number]; selected: string | null; revealed: boolean; onAnswer: (value: boolean) => void; onNext: () => void }) {
  return <section className="question-card"><div className="question-meta"><span className="question-topic">{item.topic}</span><span className="difficulty-tag">True / false</span></div><span className="eyebrow">CHECK THE CLAIM</span><h2>{item.prompt}</h2><div className="grid grid-cols-2 gap-2 mt-4">{[true, false].map(value => <button key={String(value)} disabled={revealed} className={`min-h-11 flex items-center justify-center gap-2 rounded border border-[color:var(--line)] bg-[color:var(--surface)] p-3 text-sm ${selected === String(value) ? 'border-[color:var(--green)]' : ''} ${revealed && value === item.answer ? 'bg-[color:var(--green-soft)] text-[color:var(--green)]' : ''} ${revealed && selected === String(value) && value !== item.answer ? 'bg-[color:var(--coral-soft)] text-[color:var(--coral)]' : ''}`} onClick={() => onAnswer(value)}>{value ? 'True' : 'False'}{revealed && value === item.answer && <Check size={17} />}</button>)}</div>{revealed && <div className={`explanation ${selected === String(item.answer) ? '' : 'explanation-review'}`}><strong>{selected === String(item.answer) ? 'Correct.' : 'Review the claim.'}</strong><p>{item.explanation}</p></div>}<div className="question-actions"><button className="button button-dark" disabled={!revealed} onClick={onNext}>Next question <ArrowRight size={15} /></button></div></section>
}

function Games({ record }: Shared) {
  const [mode, setMode] = useState('match')
  return <><Heading eyebrow="STUDY GAMES · PLAY TO RECALL" title="Put your knowledge in motion" description="Short challenges build the recall you need when an AP prompt gets specific." action={<span className="content-count"><Trophy size={15} /> EARN XP AS YOU PLAY</span>} /><div className="mode-tabs">{[['match', 'Match terms', Layers], ['timeline', 'Build a timeline', Activity], ['map', 'Map identification', Map], ['challenge', 'Cause & effect', Zap]].map(([id, label, Icon]) => <button key={id as string} className={mode === id ? 'mode-active' : ''} onClick={() => setMode(id as string)}><Icon size={16} />{label as string}</button>)}</div>{mode === 'match' ? <Matching record={record} /> : mode === 'timeline' ? <TimelineGame record={record} /> : mode === 'map' ? <MapGame record={record} /> : <Challenge record={record} />}</>
}

function Matching({ record }: { record: Shared['record'] }) {
  const pairs = useMemo(() => [...terms].sort(() => Math.random() - .5).slice(0, 6), []); const definitions = useMemo(() => [...pairs].sort(() => Math.random() - .5), [pairs]); const [first, setFirst] = useState<string | null>(null); const [matched, setMatched] = useState<string[]>([]); const [wrong, setWrong] = useState<string | null>(null)
  const choose = (value: string) => { if (!first) setFirst(value); else { const good = terms.find(t => t.term === first)?.definition === terms.find(t => t.term === value)?.definition; if (good) { const next = [...matched, value]; setMatched(next); record(true, 8, next.length === pairs.length ? 'matching-game' : undefined) } else { setWrong(value); window.setTimeout(() => { setWrong(null); setFirst(null) }, 500); return } setFirst(null) } }
  return <section className="game-board"><div className="game-board-heading"><div><span className="eyebrow">MATCHING GAME · 6 PAIRS</span><h2>Match the term to its field note.</h2></div><span className="timer-chip">{matched.length} / 6 matched</span></div><div className="matching-grid">{[pairs, definitions].map((group, column) => <div className="matching-column" key={column}>{group.map(item => { const value = column === 0 ? item.term : item.definition; return <button key={value} className={`match-tile ${column ? 'definition-tile' : ''} ${first === value ? 'tile-selected' : ''} ${matched.includes(item.term) ? 'tile-matched' : ''} ${wrong === value ? 'tile-wrong' : ''}`} disabled={matched.includes(item.term)} onClick={() => choose(value)}>{value}</button> })}</div>)}</div><p className="game-instruction">{matched.length === pairs.length ? 'All matched. Nice recall. Replay to try a new set.' : 'Select a term, then select the matching definition.'}</p></section>
}

function TimelineGame({ record }: { record: Shared['record'] }) {
  const [order, setOrder] = useState(() => [...timeline].sort(() => Math.random() - .5).slice(0, 5)); const [checked, setChecked] = useState(false); const [dragIndex, setDragIndex] = useState<number | null>(null); const sorted = [...order].sort((a, b) => timeline.indexOf(a) - timeline.indexOf(b)); const correct = order.every((event, i) => event.year === sorted[i].year)
  return <section className="game-board"><div className="game-board-heading"><div><span className="eyebrow">TIMELINE BUILDER · PUT EVENTS IN ORDER</span><h2>Reconstruct the sequence.</h2></div><button className="button button-outline" onClick={() => { setOrder([...timeline].sort(() => Math.random() - .5).slice(0, 5)); setChecked(false) }}><RotateCcw size={15} /> Shuffle</button></div><div className="timeline-cards">{order.map((event, i) => <div key={event.year} draggable onDragStart={() => setDragIndex(i)} onDragOver={e => e.preventDefault()} onDrop={() => { if (dragIndex !== null) setOrder(items => move(items, dragIndex, i - dragIndex)); setDragIndex(null); setChecked(false) }} className={`timeline-card ${checked ? (event.year === sorted[i].year ? 'timeline-correct' : 'timeline-incorrect') : ''}`}><span className="timeline-position">0{i + 1}</span><div><strong>{event.title}</strong><small>{event.detail}</small></div><div className="move-controls"><button disabled={!i} onClick={() => setOrder(move(order, i, -1))} aria-label="Move earlier"><ChevronLeft size={17} /></button><button disabled={i === order.length - 1} onClick={() => setOrder(move(order, i, 1))} aria-label="Move later"><ChevronRight size={17} /></button></div></div>)}</div>{checked && <p className={`timeline-result ${correct ? 'result-correct' : 'result-incorrect'}`}>{correct ? 'That’s the sequence.' : `Earliest: ${sorted[0].year} · ${sorted[0].title}. Try rearranging.`}</p>}<button className="button button-dark" onClick={() => { if (!checked && correct) record(true, 20, 'timeline-game'); setChecked(true) }}>Check sequence <ArrowRight size={15} /></button></section>
}
function move<T,>(items: T[], index: number, direction: number) { const next = [...items]; [next[index], next[index + direction]] = [next[index + direction], next[index]]; return next }

function MapGame({ record }: { record: Shared['record'] }) {
  const [index, setIndex] = useState(0); const [answer, setAnswer] = useState<string | null>(null); const target = mapPoints[index % mapPoints.length]
  const choose = (name: string) => { if (answer) return; setAnswer(name); if (name === target.name) record(true, 12) }
  return <section className="game-board"><div className="game-board-heading"><div><span className="eyebrow">MAP IDENTIFICATION · {target.type.toUpperCase()}</span><h2>Find <em>{target.name}</em> on the map.</h2></div><span className="question-count">PLACE {index % mapPoints.length + 1} / {mapPoints.length}</span></div><div className="quiz-map"><TradeMap compact />{mapPoints.map(point => <button key={point.name} className={`quiz-map-dot ${answer === point.name ? (point.name === target.name ? 'map-answer-correct' : 'map-answer-wrong') : ''}`} style={{ left: `${point.x / 7}%`, top: `${point.y / 3.1}%` }} aria-label={`Select ${point.name}`} onClick={() => choose(point.name)}><span>{point.name}</span></button>)}</div>{answer && <div className={`map-feedback ${answer === target.name ? 'result-correct' : 'result-incorrect'}`}><p>{answer === target.name ? 'Correct. ' : `That’s ${answer}. `}{target.note}</p><button className="button button-dark" onClick={() => { setIndex(i => i + 1); setAnswer(null) }}>Next <ArrowRight size={14} /></button></div>}</section>
}

const challengeFacts = [
  ['Mongol rulers protected roads and maintained a messenger network. What was a likely effect?', 'More travel and communication across Eurasia', 'Route protection and relay messaging reduced risks and improved communication.'],
  ['Indian Ocean merchants planned departures around monsoon reversals. What did this enable?', 'Predictable seasonal sailing and return journeys', 'Seasonal wind reversals made sailing schedules more predictable.'],
  ['West African rulers controlled routes carrying gold and salt. What could this help them do?', 'Accumulate wealth and strengthen states', 'Taxing and controlling trade helped states build wealth and political power.'],
  ['Trade networks carried plague alongside valuable goods. What does this show?', 'Connectivity spread harmful effects as well as benefits', 'The same connections that supported exchange also enabled pathogen transmission.'],
  ['Merchants settled abroad and kept ties with their homelands. What might follow?', 'Cultural diffusion and syncretism in port cities', 'Diasporic communities connected local and distant traditions.'],
]
function Challenge({ record }: { record: Shared['record'] }) {
  const [index, setIndex] = useState(0); const [answer, setAnswer] = useState<number | null>(null); const [score, setScore] = useState(0); const data = challengeFacts[index % challengeFacts.length]; const wrong = ['The end of all merchant credit', 'The collapse of every port city', 'A ban on interregional trade']
  const options = [data[1], wrong[index % 3], wrong[(index + 1) % 3]]
  return <section className="game-board"><div className="game-board-heading"><div><span className="eyebrow">CAUSE & EFFECT · CHALLENGE</span><h2>Read the evidence. Trace the consequence.</h2></div><span className="timer-chip"><Target size={14} /> {score} right</span></div><div className="challenge-prompt"><span className="eyebrow">SCENARIO {index % challengeFacts.length + 1} OF {challengeFacts.length}</span><h3>{data[0]}</h3></div><div className="challenge-options">{options.map((option, i) => <button key={i} disabled={answer !== null} className={answer !== null && i === 0 ? 'challenge-right' : answer === i ? 'challenge-wrong' : ''} onClick={() => { setAnswer(i); const right = i === 0; if (right) setScore(value => value + 1); record(right, right ? 15 : 3) }}><span>{String.fromCharCode(65 + i)}</span>{option}{answer !== null && i === 0 && <Check size={16} />}</button>)}</div>{answer !== null && <div className="explanation"><strong>{answer === 0 ? 'Strong historical reasoning.' : 'Review the causal link.'}</strong><p>{data[2]}</p><button onClick={() => { setIndex(i => i + 1); setAnswer(null) }}>Next scenario <ArrowRight size={14} /></button></div>}</section>
}

function Exam({ record }: Shared) {
  const [type, setType] = useState<'SAQ' | 'LEQ' | 'DBQ'>('SAQ'); const [index, setIndex] = useState(0); const [response, setResponse] = useState(''); const [saved, setSaved] = useState(false); const prompt = examPrompts[type][index % examPrompts[type].length]
  const go = (next: number) => { setIndex((next + examPrompts[type].length) % examPrompts[type].length); setResponse(''); setSaved(false) }
  return <><Heading eyebrow="AP EXAM PREP · FREE RESPONSE" title="Make the historical argument" description="Practice a defensible claim, specific evidence, and reasoning that connects them." action={<span className="content-count"><GraduationCap size={16} /> 50 PROMPTS</span>} /><div className="exam-tabs">{(['SAQ', 'LEQ', 'DBQ'] as const).map(value => <button key={value} className={type === value ? 'exam-tab-active' : ''} onClick={() => { setType(value); setIndex(0); setResponse(''); setSaved(false) }}><strong>{value}</strong><small>{value === 'SAQ' ? 'Short answer' : value === 'LEQ' ? 'Long essay' : 'Document-based'}</small><span>{examPrompts[value].length} prompts</span></button>)}</div><section className="exam-prompt"><div className="prompt-heading"><span className="eyebrow">{type} PRACTICE · PROMPT {String(index % examPrompts[type].length + 1).padStart(2, '0')} / {examPrompts[type].length}</span><button className="icon-button" aria-label="Next prompt" onClick={() => go(index + 1)}><RotateCcw size={16} /></button></div><h2>{prompt}</h2><div className="exam-skill"><Sparkles size={15} /><span>{type === 'SAQ' ? 'Answer in 2–3 sentences. Make a claim and support it with specific evidence.' : 'Build a defensible thesis, use specific evidence, and connect it through historical reasoning.'}</span></div><label className="response-label" htmlFor="exam-response">YOUR RESPONSE</label><textarea id="exam-response" value={response} onChange={e => setResponse(e.target.value)} placeholder="Start with a specific claim. Add an example from the unit. Explain why the evidence supports your claim…" rows={type === 'SAQ' ? 6 : 10} /><div className="response-footer"><span>{response.trim().split(/\s+/).filter(Boolean).length} words</span><div>{saved && <span className="saved-label"><Check size={14} /> Response saved locally</span>}<button className="button button-dark" disabled={!response.trim()} onClick={() => { localStorage.setItem(`unit2-response-${type}-${index}`, response); setSaved(true); record(true, 20, `${type}-${index}`) }}>Save response <Check size={15} /></button></div></div></section><section className="rubric-row"><div><span className="eyebrow">QUICK SELF-CHECK</span><h3>Does your response…</h3></div>{['Answer every part?', 'Use specific evidence?', 'Explain the connection?'].map(item => <label key={item} className="rubric-check"><input type="checkbox" />{item}</label>)}</section><div className="prompt-navigation"><button className="button button-outline" onClick={() => go(index - 1)}><ArrowLeft size={15} /> Previous</button><button className="button button-outline" onClick={() => go(index + 1)}>Next prompt <ArrowRight size={15} /></button></div></>
}

export default App