export type Term = { term: string; definition: string; network: string }
export type Fact = { topic: string; prompt: string; answer: string; distractors: [string, string, string]; explanation: string }
export type Question = { id: string; topic: string; prompt: string; answer: string; choices: string[]; explanation: string; difficulty: 'Easy' | 'Medium' | 'AP level' }
export type TrueFalseQuestion = { id: string; topic: string; prompt: string; answer: boolean; explanation: string }

export const terms: Term[] = [
  { term: 'Pax Mongolica', definition: 'A period of relative stability across much of Eurasia under Mongol rule that made long-distance travel and trade safer.', network: 'Mongol Empire' },
  { term: 'Caravanserai', definition: 'A roadside inn where merchants and their animals could rest, resupply, and exchange information.', network: 'Silk Roads' },
  { term: 'Diasporic community', definition: 'A community of people living outside their ancestral homeland while maintaining cultural or commercial ties to it.', network: 'Indian Ocean' },
  { term: 'Relay trade', definition: 'A system in which goods pass through multiple merchants and intermediaries instead of one trader traveling the whole route.', network: 'Silk Roads' },
  { term: 'Monsoon winds', definition: 'Seasonal wind patterns that reverse direction and made predictable sailing across the Indian Ocean possible.', network: 'Indian Ocean' },
  { term: 'Syncretism', definition: 'The blending of beliefs or cultural practices from different traditions.', network: 'Cultural exchange' },
  { term: 'Caravan', definition: 'A group of travelers, often merchants with pack animals, moving together for safety and trade.', network: 'Trans-Saharan' },
  { term: 'Pastoral nomad', definition: 'A mobile community that relies substantially on herding livestock and moving seasonally across grasslands.', network: 'Central Asia' },
  { term: 'Black Death', definition: 'The devastating fourteenth-century outbreak of plague that spread across Afro-Eurasia through trade networks.', network: 'Disease' },
  { term: 'Merchant', definition: 'A person who buys, sells, or transports goods, often across regional or long-distance networks.', network: 'Exchange' },
  { term: 'Mongol khanate', definition: 'A regional state governed by a Mongol khan after the empire expanded and was divided among successor rulers.', network: 'Mongol Empire' },
  { term: 'Silk Roads', definition: 'Overland trade routes that connected China, Central Asia, the Middle East, and the Mediterranean.', network: 'Overland' },
  { term: 'Sea Roads', definition: 'Maritime trade networks across the Indian Ocean linking East Africa, the Middle East, South Asia, and Southeast Asia.', network: 'Maritime' },
  { term: 'Sand Roads', definition: 'Trans-Saharan routes connecting North Africa and Mediterranean markets with West African states.', network: 'Trans-Saharan' },
  { term: 'Lateen sail', definition: 'A triangular sail that could catch wind from multiple directions and improve a vessel’s maneuverability.', network: 'Indian Ocean' },
  { term: 'Junk', definition: 'A large East Asian sailing vessel, often with multiple masts and bulkheads, used for cargo and travel.', network: 'Indian Ocean' },
  { term: 'Dhow', definition: 'A sailing vessel common in the western Indian Ocean, typically using a lateen sail.', network: 'Indian Ocean' },
]

export const lessons = [
  { id: 'silk', label: 'Silk Roads', subtitle: 'Across the interior', color: 'sage', summary: 'Caravans moved high-value goods across Eurasia, while relay trade and caravanserai made long routes workable.', key: 'Silk and porcelain from China, Indian cotton and spices, and Mediterranean glass traveled through merchant relays. Pastoralists supplied livestock; credit and money economies supported luxury trade. Caravanserai, imperial security, and later Mongol rule helped protect routes.' },
  { id: 'mongol', label: 'Mongol Empire', subtitle: 'Power across the steppe', color: 'clay', summary: 'Mobile pastoralists built a vast empire whose conquests were followed by a period of protected exchange.', key: 'Temujin became Genghis Khan in 1206. Merit-based leadership, horse-based warfare, discipline, and intimidation supported conquest. Pax Mongolica brought safer trade, messengers, passports, and travel; medical knowledge, numbering systems, and Uyghur script circulated. Fragmentation produced the Golden Horde, Chagatai Khanate, Ilkhanate, and Yuan Dynasty.' },
  { id: 'ocean', label: 'Indian Ocean', subtitle: 'Across the monsoon sea', color: 'blue', summary: 'Seasonal winds and ship innovations connected port cities across an expansive maritime network.', key: 'Monsoon winds, compasses, junks, dhows, and lateen sails enabled larger cargoes at lower cost than many overland journeys. Diasporic communities spread religions and syncretic practices. Srivijaya, Swahili city-states, and Great Zimbabwe were linked to this trade; Zheng He’s Ming voyages sailed widely across the ocean.' },
  { id: 'sahara', label: 'Trans-Saharan', subtitle: 'Across the desert', color: 'gold', summary: 'Camel caravans linked North African markets with prosperous states and trading cities in West Africa.', key: 'Camels and specialized saddles enabled desert crossings. Gold, salt, and enslaved people moved between North African markets and the states of Ghana, Mali, and Songhai. Timbuktu, Gao, and Jenne were important commercial and scholarly centers.' },
  { id: 'beliefs', label: 'Beliefs & Exchange', subtitle: 'Ideas on the move', color: 'rose', summary: 'Merchants and monasteries carried religions and practices, which adapted in new communities.', key: 'Buddhism spread from India into Central and East Asia, helped by merchants and monasteries. Mahayana and Theravada traditions developed distinct practices.' },
  { id: 'disease', label: 'Disease & Exchange', subtitle: 'The cost of connection', color: 'slate', summary: 'The same routes that carried goods and ideas could transmit pathogens between populations.', key: 'The plague pandemic known as the Black Death spread along Eurasian trade routes in the fourteenth century and killed a large share of Europe’s population. Plague, smallpox, malaria, and measles affected Afro-Eurasian populations.' },
]

export const facts: Fact[] = [
  { topic: 'Silk Roads', prompt: 'What made long-distance Silk Road trade possible despite its many stages?', answer: 'Relay trade and caravanserai', distractors: ['A single empire controlling every route', 'Ocean-going junks on inland rivers', 'The abolition of merchant credit'], explanation: 'Goods changed hands through relay trade, while caravanserai provided rest, supplies, and information along difficult routes.' },
  { topic: 'Silk Roads', prompt: 'Which product was especially associated with Chinese trade on the Silk Roads?', answer: 'Silk and porcelain', distractors: ['Gold and salt', 'Glass and olives', 'Ivory and cloves'], explanation: 'Chinese silk and porcelain were sought-after goods moving west through Eurasian trade networks.' },
  { topic: 'Silk Roads', prompt: 'Which South Asian products moved through Silk Road exchange?', answer: 'Cotton and spices', distractors: ['Furs and amber', 'Silver and wool', 'Olives and dates'], explanation: 'India was a source of cotton textiles and spices traded across regional and long-distance routes.' },
  { topic: 'Silk Roads', prompt: 'Why did merchants often use credit and money economies?', answer: 'To finance and simplify high-value long-distance exchange', distractors: ['To eliminate the need for intermediaries', 'To replace all regional currencies with one coin', 'To make caravan travel unnecessary'], explanation: 'Credit and monetary exchange helped merchants handle costly journeys and valuable goods.' },
  { topic: 'Silk Roads', prompt: 'Which belief spread along Silk Road routes with the help of merchants and monasteries?', answer: 'Buddhism', distractors: ['Shinto', 'Confucianism alone', 'Zoroastrianism exclusively'], explanation: 'Buddhism traveled from India through Central Asia into East Asia through commercial and religious networks.' },
  { topic: 'Silk Roads', prompt: 'What was one important function of a caravanserai?', answer: 'Providing merchants and animals a place to rest and resupply', distractors: ['Building ships for ocean voyages', 'Collecting every empire’s taxes in one place', 'Training Mongol cavalry'], explanation: 'These way stations supported safer and more reliable overland travel.' },
  { topic: 'Mongol Empire', prompt: 'What name did Temujin take in 1206?', answer: 'Genghis Khan', distractors: ['Kublai Khan', 'Ogedei Khan', 'Batu Khan'], explanation: 'A gathering of Mongol leaders recognized Temujin as Genghis Khan in 1206 after he united tribes.' },
  { topic: 'Mongol Empire', prompt: 'Which feature helped Mongol armies move rapidly across the steppe?', answer: 'Horse-based mobility and disciplined organization', distractors: ['Reliance on deep-water fleets', 'Fortified infantry alone', 'Monsoon navigation'], explanation: 'Mongol forces used skilled horse archers, mobility, discipline, and coordinated military organization.' },
  { topic: 'Mongol Empire', prompt: 'What was a major consequence of the Pax Mongolica?', answer: 'Safer trade and increased travel across much of Eurasia', distractors: ['An end to all long-distance travel', 'The collapse of every Eurasian city', 'A permanent ban on merchant exchange'], explanation: 'Mongol rule protected many routes and supported communication and trade across Eurasia.' },
  { topic: 'Mongol Empire', prompt: 'How did Mongol rulers support communication over long distances?', answer: 'They developed a messenger system and travel protections', distractors: ['They relied on monsoon winds', 'They closed roads between khanates', 'They used only local oral messengers'], explanation: 'A relay messenger network, protected routes, and travel documents helped connect the empire.' },
  { topic: 'Mongol Empire', prompt: 'Which polity was a Mongol successor khanate in Russia and the western steppe?', answer: 'Golden Horde', distractors: ['Srivijaya', 'Ghana', 'Songhai'], explanation: 'The Golden Horde was one of the major successor khanates after the empire fragmented.' },
  { topic: 'Mongol Empire', prompt: 'Which dynasty did Mongol rulers establish in China?', answer: 'Yuan Dynasty', distractors: ['Ming Dynasty', 'Gupta Dynasty', 'Abbasid Dynasty'], explanation: 'Kublai Khan established Yuan rule in China.' },
  { topic: 'Mongol Empire', prompt: 'Which sequence best describes the four broad phases of Mongol history?', answer: 'Unification, conquest, Pax Mongolica, fragmentation', distractors: ['Fragmentation, conquest, unification, Pax Mongolica', 'Trade, industrialization, reform, revolution', 'Conquest, maritime expansion, colonization, unification'], explanation: 'The unit tracks Mongol unification, expansion, protected exchange, and eventual division into successor states.' },
  { topic: 'Mongol Empire', prompt: 'Which technology or knowledge could circulate through Mongol-era exchanges?', answer: 'Medical knowledge, numbering systems, and Uyghur script', distractors: ['The printing press and steam engine', 'The compass and lateen sail only', 'Roman concrete and Greek fire only'], explanation: 'The empire helped transfer knowledge, including medical practices, numbering systems, and Uyghur writing.' },
  { topic: 'Indian Ocean', prompt: 'What natural pattern made Indian Ocean travel more predictable?', answer: 'Seasonal monsoon winds', distractors: ['Trade winds that never changed', 'The jet stream', 'Mediterranean currents'], explanation: 'Monsoon winds reverse direction seasonally, allowing sailors to plan journeys and return trips.' },
  { topic: 'Indian Ocean', prompt: 'Compared with many Silk Road journeys, what was an advantage of sea transport?', answer: 'It could move larger cargoes at lower cost', distractors: ['It never depended on weather', 'It required no specialist vessels', 'It connected only neighboring ports'], explanation: 'Ships could carry high volumes and often made maritime trade cheaper per unit of cargo.' },
  { topic: 'Indian Ocean', prompt: 'What did diasporic merchant communities often contribute to port cities?', answer: 'Cultural exchange, religious diffusion, and syncretism', distractors: ['The disappearance of local customs', 'An end to urban growth', 'A ban on interregional trade'], explanation: 'Settled merchant communities connected local ports with distant homelands and shared cultural practices.' },
  { topic: 'Indian Ocean', prompt: 'Which Southeast Asian state grew powerful by connecting maritime trade routes?', answer: 'Srivijaya', distractors: ['Mali', 'Golden Horde', 'Ghana'], explanation: 'Srivijaya benefited from its strategic location along busy maritime routes in Southeast Asia.' },
  { topic: 'Indian Ocean', prompt: 'Which vessel was commonly associated with western Indian Ocean trade?', answer: 'Dhow', distractors: ['Caravanserai', 'Junk', 'Camel litter'], explanation: 'Dhows, often using lateen sails, sailed across the western Indian Ocean.' },
  { topic: 'Indian Ocean', prompt: 'Which innovation helped ships maneuver when sailing across varied wind directions?', answer: 'Lateen sail', distractors: ['Camel saddle', 'Stirrup', 'Caravanserai'], explanation: 'The triangular lateen sail could catch wind from multiple directions.' },
  { topic: 'Indian Ocean', prompt: 'Which Ming admiral led major Chinese maritime expeditions in the fifteenth century?', answer: 'Zheng He', distractors: ['Ibn Battuta', 'Marco Polo', 'Mansa Musa'], explanation: 'Zheng He led large Ming voyages across the Indian Ocean in the early fifteenth century.' },
  { topic: 'Trans-Saharan', prompt: 'Which animal made regular long-distance desert caravans more practical?', answer: 'Arabian camel', distractors: ['Water buffalo', 'Yak', 'Llama'], explanation: 'Camels were adapted to arid environments and could carry goods over long distances.' },
  { topic: 'Trans-Saharan', prompt: 'Which paired commodities were central to trans-Saharan trade?', answer: 'Gold and salt', distractors: ['Silk and porcelain', 'Cotton and spices', 'Glass and tea'], explanation: 'Gold from West Africa and salt from Saharan sources were key goods moving through the desert routes.' },
  { topic: 'Trans-Saharan', prompt: 'Which West African empire became famous for wealth tied to trans-Saharan trade?', answer: 'Mali', distractors: ['Yuan', 'Chagatai', 'Srivijaya'], explanation: 'Mali built wealth and power by participating in and taxing gold-salt trade networks.' },
  { topic: 'Trans-Saharan', prompt: 'Which city became a well-known center of scholarship and trade in West Africa?', answer: 'Timbuktu', distractors: ['Hangzhou', 'Samarkand', 'Calicut'], explanation: 'Timbuktu was an important commercial and scholarly city connected to trans-Saharan networks.' },
  { topic: 'Trans-Saharan', prompt: 'What technology improved a camel’s ability to carry goods across the desert?', answer: 'Specialized camel saddles', distractors: ['Lateen sails', 'Compass roses', 'Ship bulkheads'], explanation: 'Camel saddles made it possible to carry heavier loads over desert routes.' },
  { topic: 'Disease & Exchange', prompt: 'How did the Black Death travel across Afro-Eurasia?', answer: 'Through trade networks linking populations', distractors: ['Only through isolated mountain villages', 'Exclusively by ocean currents', 'By a single migrating army'], explanation: 'The movement of people, goods, and disease along interconnected routes aided plague transmission.' },
  { topic: 'Disease & Exchange', prompt: 'Which statement best describes a consequence of the Black Death in Europe?', answer: 'It killed a very large share of the population, possibly up to half in some estimates', distractors: ['It had no measurable demographic impact', 'It affected only Mongol armies', 'It ended all exchange networks permanently'], explanation: 'Mortality varied by region, but the plague caused catastrophic population loss in Europe.' },
  { topic: 'Disease & Exchange', prompt: 'What broader historical pattern does the spread of plague illustrate?', answer: 'Exchange networks could transmit harmful effects as well as benefits', distractors: ['Trade moved only luxury goods', 'Technology prevented all epidemics', 'Religions never moved with merchants'], explanation: 'Connectivity moved goods and ideas, but also pathogens such as plague.' },
  { topic: 'Beliefs & Exchange', prompt: 'Where did Buddhism spread from as it moved through Central Asia?', answer: 'India', distractors: ['West Africa', 'The Andes', 'Northern Europe'], explanation: 'Buddhism originated in South Asia and spread through Central Asia toward East Asia.' },
  { topic: 'Beliefs & Exchange', prompt: 'What role did monasteries play in Buddhist expansion?', answer: 'They offered communities for teaching, worship, and travel along routes', distractors: ['They replaced merchant shipping', 'They served as Mongol postal stations only', 'They prohibited local adaptation'], explanation: 'Monasteries supported religious learning and helped travelers and merchants carry Buddhism.' },
  { topic: 'Beliefs & Exchange', prompt: 'Which branch became especially influential across Central and East Asia?', answer: 'Mahayana Buddhism', distractors: ['Theravada Buddhism exclusively', 'Shinto Buddhism', 'Latin Christianity'], explanation: 'Mahayana traditions spread widely into Central and East Asia, while Theravada remained influential in South and Southeast Asia.' },
  { topic: 'Exchange & Society', prompt: 'How could trade affect labor in connected regions?', answer: 'It encouraged specialization to produce goods for wider markets', distractors: ['It eliminated all occupational differences', 'It prevented urban growth', 'It made agricultural production unnecessary'], explanation: 'Demand from trade encouraged regions and workers to specialize in particular products.' },
  { topic: 'Exchange & Society', prompt: 'How could trade contribute to state building?', answer: 'Rulers gained wealth by controlling routes and taxing exchange', distractors: ['Merchants ended all political authority', 'Trade reduced all revenue to zero', 'States could no longer support armies'], explanation: 'Control of routes, ports, and market taxes helped rulers accumulate wealth and strengthen states.' },
  { topic: 'Exchange & Society', prompt: 'Which change in consumption could long-distance trade encourage?', answer: 'Greater access to goods previously unavailable locally', distractors: ['Universal access to every luxury good', 'The end of regional markets', 'A ban on imported products'], explanation: 'Trade altered consumption by bringing new and sometimes luxury goods into distant markets.' },
  { topic: 'Comparison', prompt: 'What did the Silk Roads and Indian Ocean network have in common?', answer: 'Both connected distant regions and spread goods and ideas', distractors: ['Both relied only on camels', 'Neither moved religious beliefs', 'Both were controlled by one state throughout'], explanation: 'Both networks connected Afro-Eurasian regions and carried products, beliefs, and technologies.' },
  { topic: 'Comparison', prompt: 'Which contrast between the networks is most accurate?', answer: 'Silk Roads were primarily overland; Indian Ocean routes were maritime', distractors: ['Silk Roads were maritime; Indian Ocean routes crossed deserts', 'Both were only regional river routes', 'Indian Ocean trade began after 1450'], explanation: 'The routes differed in transportation and geography, even as both supported long-distance exchange.' },
  { topic: 'Historical Skills', prompt: 'Which is a cause-and-effect relationship in Unit 2?', answer: 'Mongol protection of routes contributed to increased Eurasian travel and trade', distractors: ['More travel caused the invention of the camel', 'Monsoons were created by Indian merchants', 'Disease ended before trade began'], explanation: 'The Pax Mongolica increased security and communication, helping travel and exchange grow.' },
  { topic: 'Historical Skills', prompt: 'What is an example of continuity in exchange from 1200 to 1450?', answer: 'Merchants continued to connect distant regions through established routes', distractors: ['All overland trade disappeared', 'Religious exchange stopped entirely', 'Every regional state became a maritime empire'], explanation: 'Networks changed and expanded, but long-distance exchange remained a persistent feature.' },
]

const variants = [(fact: Fact) => fact.prompt, (fact: Fact) => `A student reviewing ${fact.topic.toLowerCase()} asks: ${fact.prompt.charAt(0).toLowerCase()}${fact.prompt.slice(1)}`, (fact: Fact) => `Which choice best explains this development? ${fact.prompt}`]
export const questions: Question[] = facts.flatMap((fact, fi) => variants.flatMap((variant, vi) => (['Easy', 'Medium', 'AP level'] as const).map((difficulty, di) => {
  const choices = [fact.answer, ...fact.distractors]; const shift = (fi + vi + di) % choices.length
  return { id: `${fi}-${vi}-${di}`, topic: fact.topic, prompt: variant(fact), answer: fact.answer, choices: [...choices.slice(shift), ...choices.slice(0, shift)], explanation: fact.explanation, difficulty }
})))

export const trueFalseQuestions: TrueFalseQuestion[] = [
  { id: 'tf1', topic: 'Silk Roads', prompt: 'Caravanserai offered merchants and animals places to rest and resupply.', answer: true, explanation: 'These roadside inns supported the long journeys required for overland trade.' },
  { id: 'tf2', topic: 'Silk Roads', prompt: 'On the Silk Roads, each merchant typically traveled the entire route from China to the Mediterranean.', answer: false, explanation: 'Relay trade meant goods commonly passed between multiple merchants.' },
  { id: 'tf3', topic: 'Silk Roads', prompt: 'Chinese silk and porcelain were important goods in Silk Road exchange.', answer: true, explanation: 'These high-value goods traveled west through Eurasian networks.' },
  { id: 'tf4', topic: 'Beliefs & Exchange', prompt: 'Buddhism spread from India through Central Asia toward East Asia.', answer: true, explanation: 'Merchants and monasteries helped carry Buddhism along overland routes.' },
  { id: 'tf5', topic: 'Beliefs & Exchange', prompt: 'Religious traditions remained completely unchanged as they spread to new regions.', answer: false, explanation: 'Beliefs adapted in new cultural settings; this process could produce syncretism.' },
  { id: 'tf6', topic: 'Mongol Empire', prompt: 'Temujin became Genghis Khan in 1206 after uniting Mongol tribes.', answer: true, explanation: 'Mongol unification under Genghis Khan preceded the period of conquest.' },
  { id: 'tf7', topic: 'Mongol Empire', prompt: 'The Pax Mongolica made long-distance trade and travel less secure.', answer: false, explanation: 'Mongol protection of routes made many journeys safer and supported exchange.' },
  { id: 'tf8', topic: 'Mongol Empire', prompt: 'The Mongol Empire eventually divided into successor khanates, including the Golden Horde and Ilkhanate.', answer: true, explanation: 'Political fragmentation produced multiple regional Mongol successor states.' },
  { id: 'tf9', topic: 'Mongol Empire', prompt: 'Mongol military success depended in part on mobility, discipline, and horse-based warfare.', answer: true, explanation: 'Organized, mobile cavalry forces were a central Mongol military advantage.' },
  { id: 'tf10', topic: 'Indian Ocean', prompt: 'Monsoon winds reverse direction seasonally and helped sailors plan voyages.', answer: true, explanation: 'The seasonal pattern supported predictable outbound and return trips.' },
  { id: 'tf11', topic: 'Indian Ocean', prompt: 'The Indian Ocean network could carry larger cargoes at lower cost than many overland routes.', answer: true, explanation: 'Ships offered substantial cargo capacity and lower costs per unit for many goods.' },
  { id: 'tf12', topic: 'Indian Ocean', prompt: 'A dhow was a large East Asian vessel associated with Chinese maritime trade.', answer: false, explanation: 'Dhows were common in the western Indian Ocean; junks were associated with East Asian shipping.' },
  { id: 'tf13', topic: 'Indian Ocean', prompt: 'Diasporic communities could help spread religions and create cultural blending in port cities.', answer: true, explanation: 'Communities abroad maintained links while exchanging ideas and practices with local populations.' },
  { id: 'tf14', topic: 'Indian Ocean', prompt: 'Zheng He led Ming voyages across the Indian Ocean in the fifteenth century.', answer: true, explanation: 'His expeditions sailed widely through the Indian Ocean world between 1405 and 1433.' },
  { id: 'tf15', topic: 'Trans-Saharan', prompt: 'Camel saddles helped make long-distance trans-Saharan trade more practical.', answer: true, explanation: 'Camels and specialized saddles enabled the transport of heavier loads across desert routes.' },
  { id: 'tf16', topic: 'Trans-Saharan', prompt: 'Gold and salt were important goods exchanged through trans-Saharan networks.', answer: true, explanation: 'These commodities linked West African producers and Saharan sources to North African markets.' },
  { id: 'tf17', topic: 'Trans-Saharan', prompt: 'Timbuktu, Gao, and Jenne were important cities associated with West African trade.', answer: true, explanation: 'These cities connected commercial, political, and scholarly activity in the region.' },
  { id: 'tf18', topic: 'Disease & Exchange', prompt: 'The Black Death spread across Afro-Eurasia partly through connected trade routes.', answer: true, explanation: 'Movement along exchange networks also transmitted pathogens.' },
  { id: 'tf19', topic: 'Disease & Exchange', prompt: 'The Black Death had no major demographic impact on Europe.', answer: false, explanation: 'The plague caused catastrophic mortality, killing a very large share of Europe’s population.' },
  { id: 'tf20', topic: 'Exchange & Society', prompt: 'Trade could encourage labor specialization and help rulers build wealth by taxing routes.', answer: true, explanation: 'Demand and control of exchange supported specialization and state-building.' },
]

export const timeline = [
  { year: '1206', title: 'Temujin becomes Genghis Khan', detail: 'Mongol leaders unite under Temujin, beginning a new phase of steppe power.' },
  { year: '1219–1221', title: 'Mongol campaigns in Central Asia', detail: 'Conquests connect territories and reshape trade routes across Eurasia.' },
  { year: '1271', title: 'Yuan Dynasty proclaimed', detail: 'Kublai Khan establishes the Yuan dynasty in China.' },
  { year: '1279', title: 'Mongol conquest of Song China completed', detail: 'Mongol rule extends across China and consolidates the Yuan period.' },
  { year: 'c. 1300', title: 'Pax Mongolica at its height', detail: 'Trade, travel, and communication intensify across much of the empire.' },
  { year: '1347–1351', title: 'Plague spreads across Europe', detail: 'The Black Death moves along interconnected trade and travel networks.' },
  { year: '1368', title: 'Yuan rule ends in China', detail: 'The Ming dynasty replaces Yuan rule as Mongol political unity fragments.' },
  { year: '1405–1433', title: 'Zheng He’s voyages', detail: 'Ming fleets travel widely across the Indian Ocean.' },
]

export const examPrompts: Record<'SAQ' | 'LEQ' | 'DBQ', string[]> = {
  SAQ: ['Identify one factor that contributed to the growth of exchange networks after 1200 CE.','Explain one way Mongol rule facilitated trade across Eurasia.','Describe one technology that supported Indian Ocean trade.','Explain one effect of the spread of Buddhism along the Silk Roads.','Identify one similarity between Silk Road and Indian Ocean trade.','Explain one way trans-Saharan trade contributed to state building.','Describe one consequence of the spread of the Black Death.','Explain how monsoon winds influenced Indian Ocean merchants.','Identify one way diasporic communities encouraged cultural exchange.','Explain one military advantage used by Mongol armies.','Describe one way camel technology affected trans-Saharan trade.','Explain one way trade altered consumption patterns after 1200.','Identify one example of technological diffusion under Mongol rule.','Explain one difference between the goods traded on the Silk Roads and Sand Roads.','Describe one way caravanserai supported overland exchange.','Explain one way Indian Ocean trade contributed to syncretism.','Identify one continuity in Afro-Eurasian trade from 1200 to 1450.','Explain one way merchants helped spread religious beliefs.','Describe one effect of maritime innovations on trade volume.','Explain one cause and one effect of the growth of exchange networks after 1200 CE.'],
  LEQ: ['Evaluate the extent to which the Mongol Empire transformed patterns of Eurasian exchange from 1200 to 1450.','Compare the Silk Roads and Indian Ocean trade networks in the period 1200–1450.','Evaluate the extent to which technological innovations were the primary cause of expanding trade after 1200.','Evaluate the extent to which trade networks contributed to state building in Afro-Eurasia from 1200 to 1450.','Compare the effects of overland and maritime trade on the movement of beliefs.','Evaluate the extent to which the Black Death was a consequence of increased Afro-Eurasian connectivity.','Analyze continuities and changes in long-distance trade from 1200 to 1450.','Evaluate the role of environmental factors in the expansion of Indian Ocean and trans-Saharan trade.','Compare the political effects of Silk Road and trans-Saharan exchange.','Evaluate the extent to which merchant communities shaped cultural exchange in the Indian Ocean basin.','Analyze the causes and effects of the growth of exchange networks after 1200 CE.','Evaluate the significance of the Pax Mongolica in larger patterns of continuity and change.','Compare the ways pastoral peoples and maritime states participated in regional exchange.','Evaluate how trade altered social and economic life in Afro-Eurasian societies.','Analyze the relationship between commercial exchange and the spread of religious traditions from 1200 to 1450.'],
  DBQ: ['Evaluate how Mongol rule affected trade, communication, and travel across Eurasia.','Evaluate the relative importance of technology and geography in Indian Ocean exchange.','Analyze how trade networks affected the spread of religious and cultural practices.','Evaluate the extent to which trans-Saharan trade strengthened West African states.','Analyze the effects of growing Afro-Eurasian connectivity on disease transmission.','Evaluate how far trade networks changed social hierarchies and economic specialization.','Compare political authorities’ approaches to controlling routes and ports.','Evaluate the roles of merchant diasporas in shaping Indian Ocean port cities.','Analyze how environmental conditions shaped commercial strategies across two networks.','Evaluate the extent to which Mongol expansion created both destruction and opportunity.','Analyze the relationship between luxury goods, credit, and Silk Road commerce.','Evaluate how technological exchange contributed to changes in military power.','Compare continuity and change in Afro-Eurasian exchange before and after Mongol expansion.','Analyze the economic and cultural effects of Indian Ocean maritime innovations.','Evaluate the extent to which exchange networks created interdependence across Afro-Eurasia.'],
}

export const mapPoints = [
  { name: 'Chang’an', x: 76, y: 39, type: 'Silk Roads', note: 'Eastern terminus of major overland routes; Chinese silk and porcelain traveled west.' },
  { name: 'Samarkand', x: 57, y: 34, type: 'Silk Roads', note: 'A Central Asian crossroads connecting merchants and caravans.' },
  { name: 'Constantinople', x: 45, y: 40, type: 'Silk Roads', note: 'A strategic Mediterranean gateway linking Europe and Asia.' },
  { name: 'Calicut', x: 60, y: 62, type: 'Indian Ocean', note: 'A major Indian Ocean port shaped by monsoon sailing and merchant exchange.' },
  { name: 'Kilwa', x: 49, y: 75, type: 'Indian Ocean', note: 'A Swahili coast city connected to African gold and Indian Ocean commerce.' },
  { name: 'Timbuktu', x: 34, y: 56, type: 'Trans-Saharan', note: 'A West African commercial and scholarly center linked to trans-Saharan caravans.' },
  { name: 'Mogadishu', x: 52, y: 62, type: 'Indian Ocean', note: 'A Swahili coast port connected to regional and overseas maritime trade.' },
]
export const badges = [{ name: 'Silk Road Scholar', icon: 'route', threshold: 20 },{ name: 'Trade Network Expert', icon: 'globe', threshold: 35 },{ name: 'Mongol Master', icon: 'crown', threshold: 50 },{ name: 'Pax Mongolica Pro', icon: 'shield', threshold: 65 },{ name: 'Indian Ocean Navigator', icon: 'compass', threshold: 80 },{ name: 'Sahara Specialist', icon: 'sun', threshold: 90 },{ name: 'AP World Champion', icon: 'trophy', threshold: 100 }]